-- +goose Up
-- +goose StatementBegin

CREATE TABLE problem_lists (
    id          BIGSERIAL PRIMARY KEY,
    slug        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    description TEXT,
    source_url  TEXT,
    sort_order  INT NOT NULL DEFAULT 0
);

CREATE TABLE problem_list_items (
    list_id     BIGINT NOT NULL REFERENCES problem_lists(id) ON DELETE CASCADE,
    position    INT NOT NULL,
    section     TEXT,
    problem_id  BIGINT NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
    PRIMARY KEY (list_id, position),
    UNIQUE (list_id, problem_id)
);

CREATE INDEX problem_list_items_problem_idx ON problem_list_items (problem_id);

INSERT INTO problem_lists (slug, name, description, source_url, sort_order)
VALUES
  ('blind-75', 'Blind 75', 'A compact set of core interview problems organized for pattern coverage.', 'https://www.crackr.dev/blind75', 10),
  ('neetcode-150', 'NeetCode 150', 'Blind 75 plus a broader set of common LeetCode interview problems.', 'https://www.crackr.dev/neetcode150', 20)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    source_url = EXCLUDED.source_url,
    sort_order = EXCLUDED.sort_order;

WITH items(list_slug, position, leetcode_slug) AS (
  VALUES
    ('blind-75', 1, 'two-sum'),
    ('blind-75', 2, 'contains-duplicate'),
    ('blind-75', 3, 'top-k-frequent-elements'),
    ('blind-75', 4, 'product-of-array-except-self'),
    ('blind-75', 5, 'longest-consecutive-sequence'),
    ('blind-75', 6, '3sum'),
    ('blind-75', 7, 'container-with-most-water'),
    ('blind-75', 8, 'best-time-to-buy-and-sell-stock'),
    ('blind-75', 9, 'combination-sum'),
    ('blind-75', 10, 'insert-interval'),
    ('blind-75', 11, 'merge-intervals'),
    ('blind-75', 12, 'non-overlapping-intervals'),
    ('blind-75', 13, 'meeting-rooms'),
    ('blind-75', 14, 'meeting-rooms-ii'),
    ('blind-75', 15, 'missing-number'),
    ('blind-75', 16, 'valid-anagram'),
    ('blind-75', 17, 'group-anagrams'),
    ('blind-75', 18, 'encode-and-decode-strings'),
    ('blind-75', 19, 'valid-palindrome'),
    ('blind-75', 20, 'longest-substring-without-repeating-characters'),
    ('blind-75', 21, 'longest-repeating-character-replacement'),
    ('blind-75', 22, 'minimum-window-substring'),
    ('blind-75', 23, 'longest-palindromic-substring'),
    ('blind-75', 24, 'palindromic-substrings'),
    ('blind-75', 25, 'valid-parentheses'),
    ('blind-75', 26, 'rotate-image'),
    ('blind-75', 27, 'spiral-matrix'),
    ('blind-75', 28, 'set-matrix-zeroes'),
    ('blind-75', 29, 'find-minimum-in-rotated-sorted-array'),
    ('blind-75', 30, 'search-in-rotated-sorted-array'),
    ('blind-75', 31, 'reverse-linked-list'),
    ('blind-75', 32, 'merge-two-sorted-lists'),
    ('blind-75', 33, 'linked-list-cycle'),
    ('blind-75', 34, 'reorder-list'),
    ('blind-75', 35, 'remove-nth-node-from-end-of-list'),
    ('blind-75', 36, 'merge-k-sorted-lists'),
    ('blind-75', 37, 'invert-binary-tree'),
    ('blind-75', 38, 'maximum-depth-of-binary-tree'),
    ('blind-75', 39, 'same-tree'),
    ('blind-75', 40, 'subtree-of-another-tree'),
    ('blind-75', 41, 'binary-tree-level-order-traversal'),
    ('blind-75', 42, 'construct-binary-tree-from-preorder-and-inorder-traversal'),
    ('blind-75', 43, 'binary-tree-maximum-path-sum'),
    ('blind-75', 44, 'serialize-and-deserialize-binary-tree'),
    ('blind-75', 45, 'lowest-common-ancestor-of-a-binary-search-tree'),
    ('blind-75', 46, 'validate-binary-search-tree'),
    ('blind-75', 47, 'kth-smallest-element-in-a-bst'),
    ('blind-75', 48, 'implement-trie-prefix-tree'),
    ('blind-75', 49, 'design-add-and-search-words-data-structure'),
    ('blind-75', 50, 'word-search-ii'),
    ('blind-75', 51, 'find-median-from-data-stream'),
    ('blind-75', 52, 'word-search'),
    ('blind-75', 53, 'number-of-islands'),
    ('blind-75', 54, 'clone-graph'),
    ('blind-75', 55, 'pacific-atlantic-water-flow'),
    ('blind-75', 56, 'course-schedule'),
    ('blind-75', 57, 'number-of-connected-components-in-an-undirected-graph'),
    ('blind-75', 58, 'graph-valid-tree'),
    ('blind-75', 59, 'alien-dictionary'),
    ('blind-75', 60, 'climbing-stairs'),
    ('blind-75', 61, 'house-robber'),
    ('blind-75', 62, 'house-robber-ii'),
    ('blind-75', 63, 'decode-ways'),
    ('blind-75', 64, 'coin-change'),
    ('blind-75', 65, 'maximum-product-subarray'),
    ('blind-75', 66, 'word-break'),
    ('blind-75', 67, 'longest-increasing-subsequence'),
    ('blind-75', 68, 'unique-paths'),
    ('blind-75', 69, 'jump-game'),
    ('blind-75', 70, 'combination-sum-iv'),
    ('blind-75', 71, 'maximum-subarray'),
    ('blind-75', 72, 'number-of-1-bits'),
    ('blind-75', 73, 'counting-bits'),
    ('blind-75', 74, 'reverse-bits'),
    ('blind-75', 75, 'sum-of-two-integers'),
    ('neetcode-150', 1, 'contains-duplicate'),
    ('neetcode-150', 2, 'valid-anagram'),
    ('neetcode-150', 3, 'two-sum'),
    ('neetcode-150', 4, 'group-anagrams'),
    ('neetcode-150', 5, 'top-k-frequent-elements'),
    ('neetcode-150', 6, 'product-of-array-except-self'),
    ('neetcode-150', 7, 'valid-sudoku'),
    ('neetcode-150', 8, 'encode-and-decode-strings'),
    ('neetcode-150', 9, 'longest-consecutive-sequence'),
    ('neetcode-150', 10, 'valid-palindrome'),
    ('neetcode-150', 11, 'two-sum-ii-input-array-is-sorted'),
    ('neetcode-150', 12, '3sum'),
    ('neetcode-150', 13, 'container-with-most-water'),
    ('neetcode-150', 14, 'trapping-rain-water'),
    ('neetcode-150', 15, 'best-time-to-buy-and-sell-stock'),
    ('neetcode-150', 16, 'longest-substring-without-repeating-characters'),
    ('neetcode-150', 17, 'longest-repeating-character-replacement'),
    ('neetcode-150', 18, 'permutation-in-string'),
    ('neetcode-150', 19, 'minimum-window-substring'),
    ('neetcode-150', 20, 'sliding-window-maximum'),
    ('neetcode-150', 21, 'valid-parentheses'),
    ('neetcode-150', 22, 'min-stack'),
    ('neetcode-150', 23, 'evaluate-reverse-polish-notation'),
    ('neetcode-150', 24, 'generate-parentheses'),
    ('neetcode-150', 25, 'daily-temperatures'),
    ('neetcode-150', 26, 'car-fleet'),
    ('neetcode-150', 27, 'largest-rectangle-in-histogram'),
    ('neetcode-150', 28, 'binary-search'),
    ('neetcode-150', 29, 'search-a-2d-matrix'),
    ('neetcode-150', 30, 'koko-eating-bananas'),
    ('neetcode-150', 31, 'find-minimum-in-rotated-sorted-array'),
    ('neetcode-150', 32, 'search-in-rotated-sorted-array'),
    ('neetcode-150', 33, 'time-based-key-value-store'),
    ('neetcode-150', 34, 'median-of-two-sorted-arrays'),
    ('neetcode-150', 35, 'reverse-linked-list'),
    ('neetcode-150', 36, 'merge-two-sorted-lists'),
    ('neetcode-150', 37, 'linked-list-cycle'),
    ('neetcode-150', 38, 'reorder-list'),
    ('neetcode-150', 39, 'remove-nth-node-from-end-of-list'),
    ('neetcode-150', 40, 'copy-list-with-random-pointer'),
    ('neetcode-150', 41, 'add-two-numbers'),
    ('neetcode-150', 42, 'find-the-duplicate-number'),
    ('neetcode-150', 43, 'lru-cache'),
    ('neetcode-150', 44, 'merge-k-sorted-lists'),
    ('neetcode-150', 45, 'reverse-nodes-in-k-group'),
    ('neetcode-150', 46, 'invert-binary-tree'),
    ('neetcode-150', 47, 'maximum-depth-of-binary-tree'),
    ('neetcode-150', 48, 'diameter-of-binary-tree'),
    ('neetcode-150', 49, 'balanced-binary-tree'),
    ('neetcode-150', 50, 'same-tree'),
    ('neetcode-150', 51, 'subtree-of-another-tree'),
    ('neetcode-150', 52, 'lowest-common-ancestor-of-a-binary-search-tree'),
    ('neetcode-150', 53, 'binary-tree-level-order-traversal'),
    ('neetcode-150', 54, 'binary-tree-right-side-view'),
    ('neetcode-150', 55, 'count-good-nodes-in-binary-tree'),
    ('neetcode-150', 56, 'validate-binary-search-tree'),
    ('neetcode-150', 57, 'kth-smallest-element-in-a-bst'),
    ('neetcode-150', 58, 'construct-binary-tree-from-preorder-and-inorder-traversal'),
    ('neetcode-150', 59, 'binary-tree-maximum-path-sum'),
    ('neetcode-150', 60, 'serialize-and-deserialize-binary-tree'),
    ('neetcode-150', 61, 'implement-trie-prefix-tree'),
    ('neetcode-150', 62, 'design-add-and-search-words-data-structure'),
    ('neetcode-150', 63, 'word-search-ii'),
    ('neetcode-150', 64, 'kth-largest-element-in-a-stream'),
    ('neetcode-150', 65, 'last-stone-weight'),
    ('neetcode-150', 66, 'k-closest-points-to-origin'),
    ('neetcode-150', 67, 'kth-largest-element-in-an-array'),
    ('neetcode-150', 68, 'task-scheduler'),
    ('neetcode-150', 69, 'design-twitter'),
    ('neetcode-150', 70, 'find-median-from-data-stream'),
    ('neetcode-150', 71, 'subsets'),
    ('neetcode-150', 72, 'combination-sum'),
    ('neetcode-150', 73, 'combination-sum-ii'),
    ('neetcode-150', 74, 'permutations'),
    ('neetcode-150', 75, 'subsets-ii'),
    ('neetcode-150', 76, 'word-search'),
    ('neetcode-150', 77, 'palindrome-partitioning'),
    ('neetcode-150', 78, 'letter-combinations-of-a-phone-number'),
    ('neetcode-150', 79, 'n-queens'),
    ('neetcode-150', 80, 'number-of-islands'),
    ('neetcode-150', 81, 'max-area-of-island'),
    ('neetcode-150', 82, 'clone-graph'),
    ('neetcode-150', 83, 'walls-and-gates'),
    ('neetcode-150', 84, 'rotting-oranges'),
    ('neetcode-150', 85, 'pacific-atlantic-water-flow'),
    ('neetcode-150', 86, 'surrounded-regions'),
    ('neetcode-150', 87, 'course-schedule'),
    ('neetcode-150', 88, 'course-schedule-ii'),
    ('neetcode-150', 89, 'graph-valid-tree'),
    ('neetcode-150', 90, 'number-of-connected-components-in-an-undirected-graph'),
    ('neetcode-150', 91, 'redundant-connection'),
    ('neetcode-150', 92, 'word-ladder'),
    ('neetcode-150', 93, 'reconstruct-itinerary'),
    ('neetcode-150', 94, 'min-cost-to-connect-all-points'),
    ('neetcode-150', 95, 'network-delay-time'),
    ('neetcode-150', 96, 'swim-in-rising-water'),
    ('neetcode-150', 97, 'alien-dictionary'),
    ('neetcode-150', 98, 'cheapest-flights-within-k-stops'),
    ('neetcode-150', 99, 'climbing-stairs'),
    ('neetcode-150', 100, 'min-cost-climbing-stairs'),
    ('neetcode-150', 101, 'house-robber'),
    ('neetcode-150', 102, 'house-robber-ii'),
    ('neetcode-150', 103, 'longest-palindromic-substring'),
    ('neetcode-150', 104, 'palindromic-substrings'),
    ('neetcode-150', 105, 'decode-ways'),
    ('neetcode-150', 106, 'coin-change'),
    ('neetcode-150', 107, 'maximum-product-subarray'),
    ('neetcode-150', 108, 'word-break'),
    ('neetcode-150', 109, 'longest-increasing-subsequence'),
    ('neetcode-150', 110, 'partition-equal-subset-sum'),
    ('neetcode-150', 111, 'unique-paths'),
    ('neetcode-150', 112, 'longest-common-subsequence'),
    ('neetcode-150', 113, 'best-time-to-buy-and-sell-stock-with-cooldown'),
    ('neetcode-150', 114, 'coin-change-ii'),
    ('neetcode-150', 115, 'target-sum'),
    ('neetcode-150', 116, 'interleaving-string'),
    ('neetcode-150', 117, 'longest-increasing-path-in-a-matrix'),
    ('neetcode-150', 118, 'distinct-subsequences'),
    ('neetcode-150', 119, 'edit-distance'),
    ('neetcode-150', 120, 'burst-balloons'),
    ('neetcode-150', 121, 'regular-expression-matching'),
    ('neetcode-150', 122, 'maximum-subarray'),
    ('neetcode-150', 123, 'jump-game'),
    ('neetcode-150', 124, 'jump-game-ii'),
    ('neetcode-150', 125, 'gas-station'),
    ('neetcode-150', 126, 'hand-of-straights'),
    ('neetcode-150', 127, 'merge-triplets-to-form-target-triplet'),
    ('neetcode-150', 128, 'partition-labels'),
    ('neetcode-150', 129, 'valid-parenthesis-string'),
    ('neetcode-150', 130, 'insert-interval'),
    ('neetcode-150', 131, 'merge-intervals'),
    ('neetcode-150', 132, 'non-overlapping-intervals'),
    ('neetcode-150', 133, 'meeting-rooms'),
    ('neetcode-150', 134, 'meeting-rooms-ii'),
    ('neetcode-150', 135, 'minimum-interval-to-include-each-query'),
    ('neetcode-150', 136, 'rotate-image'),
    ('neetcode-150', 137, 'spiral-matrix'),
    ('neetcode-150', 138, 'set-matrix-zeroes'),
    ('neetcode-150', 139, 'happy-number'),
    ('neetcode-150', 140, 'plus-one'),
    ('neetcode-150', 141, 'powx-n'),
    ('neetcode-150', 142, 'multiply-strings'),
    ('neetcode-150', 143, 'detect-squares'),
    ('neetcode-150', 144, 'single-number'),
    ('neetcode-150', 145, 'number-of-1-bits'),
    ('neetcode-150', 146, 'counting-bits'),
    ('neetcode-150', 147, 'reverse-bits'),
    ('neetcode-150', 148, 'missing-number'),
    ('neetcode-150', 149, 'sum-of-two-integers'),
    ('neetcode-150', 150, 'reverse-integer')
)
INSERT INTO problem_list_items (list_id, position, problem_id)
SELECT pl.id, items.position, p.id
FROM items
JOIN problem_lists pl ON pl.slug = items.list_slug
JOIN problems p ON p.leetcode_slug = items.leetcode_slug
ON CONFLICT (list_id, problem_id) DO NOTHING;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS problem_list_items;
DROP TABLE IF EXISTS problem_lists;
-- +goose StatementEnd
