-- +goose Up
-- +goose StatementBegin

-- ─── Sections: Blind 75 ──────────────────────────────────────────────────────
UPDATE problem_list_items pli
SET section = upd.section
FROM (VALUES
    (1,  'Arrays & Hashing'),
    (2,  'Arrays & Hashing'),
    (3,  'Arrays & Hashing'),
    (4,  'Arrays & Hashing'),
    (5,  'Arrays & Hashing'),
    (6,  'Two Pointers'),
    (7,  'Two Pointers'),
    (8,  'Sliding Window'),
    (9,  'Backtracking'),
    (10, 'Intervals'),
    (11, 'Intervals'),
    (12, 'Intervals'),
    (13, 'Intervals'),
    (14, 'Intervals'),
    (15, 'Bit Manipulation'),
    (16, 'Arrays & Hashing'),
    (17, 'Arrays & Hashing'),
    (18, 'Arrays & Hashing'),
    (19, 'Two Pointers'),
    (20, 'Sliding Window'),
    (21, 'Sliding Window'),
    (22, 'Sliding Window'),
    (23, '1D Dynamic Programming'),
    (24, '1D Dynamic Programming'),
    (25, 'Stack'),
    (26, 'Math & Geometry'),
    (27, 'Math & Geometry'),
    (28, 'Math & Geometry'),
    (29, 'Binary Search'),
    (30, 'Binary Search'),
    (31, 'Linked List'),
    (32, 'Linked List'),
    (33, 'Linked List'),
    (34, 'Linked List'),
    (35, 'Linked List'),
    (36, 'Linked List'),
    (37, 'Trees'),
    (38, 'Trees'),
    (39, 'Trees'),
    (40, 'Trees'),
    (41, 'Trees'),
    (42, 'Trees'),
    (43, 'Trees'),
    (44, 'Trees'),
    (45, 'Trees'),
    (46, 'Trees'),
    (47, 'Trees'),
    (48, 'Tries'),
    (49, 'Tries'),
    (50, 'Tries'),
    (51, 'Heap / Priority Queue'),
    (52, 'Backtracking'),
    (53, 'Graphs'),
    (54, 'Graphs'),
    (55, 'Graphs'),
    (56, 'Graphs'),
    (57, 'Graphs'),
    (58, 'Graphs'),
    (59, 'Advanced Graphs'),
    (60, '1D Dynamic Programming'),
    (61, '1D Dynamic Programming'),
    (62, '1D Dynamic Programming'),
    (63, '1D Dynamic Programming'),
    (64, '1D Dynamic Programming'),
    (65, '1D Dynamic Programming'),
    (66, '1D Dynamic Programming'),
    (67, '1D Dynamic Programming'),
    (68, '2D Dynamic Programming'),
    (69, 'Greedy'),
    (70, '1D Dynamic Programming'),
    (71, 'Greedy'),
    (72, 'Bit Manipulation'),
    (73, 'Bit Manipulation'),
    (74, 'Bit Manipulation'),
    (75, 'Bit Manipulation')
) AS upd(pos, section),
problem_lists pl
WHERE pl.slug = 'blind-75'
  AND pli.list_id = pl.id
  AND pli.position = upd.pos;

-- ─── Sections: NeetCode 150 ──────────────────────────────────────────────────
UPDATE problem_list_items pli
SET section = upd.section
FROM (VALUES
    (1,   'Arrays & Hashing'),
    (2,   'Arrays & Hashing'),
    (3,   'Arrays & Hashing'),
    (4,   'Arrays & Hashing'),
    (5,   'Arrays & Hashing'),
    (6,   'Arrays & Hashing'),
    (7,   'Arrays & Hashing'),
    (8,   'Arrays & Hashing'),
    (9,   'Arrays & Hashing'),
    (10,  'Two Pointers'),
    (11,  'Two Pointers'),
    (12,  'Two Pointers'),
    (13,  'Two Pointers'),
    (14,  'Two Pointers'),
    (15,  'Sliding Window'),
    (16,  'Sliding Window'),
    (17,  'Sliding Window'),
    (18,  'Sliding Window'),
    (19,  'Sliding Window'),
    (20,  'Sliding Window'),
    (21,  'Stack'),
    (22,  'Stack'),
    (23,  'Stack'),
    (24,  'Stack'),
    (25,  'Stack'),
    (26,  'Stack'),
    (27,  'Stack'),
    (28,  'Binary Search'),
    (29,  'Binary Search'),
    (30,  'Binary Search'),
    (31,  'Binary Search'),
    (32,  'Binary Search'),
    (33,  'Binary Search'),
    (34,  'Binary Search'),
    (35,  'Linked List'),
    (36,  'Linked List'),
    (37,  'Linked List'),
    (38,  'Linked List'),
    (39,  'Linked List'),
    (40,  'Linked List'),
    (41,  'Linked List'),
    (42,  'Linked List'),
    (43,  'Linked List'),
    (44,  'Linked List'),
    (45,  'Linked List'),
    (46,  'Trees'),
    (47,  'Trees'),
    (48,  'Trees'),
    (49,  'Trees'),
    (50,  'Trees'),
    (51,  'Trees'),
    (52,  'Trees'),
    (53,  'Trees'),
    (54,  'Trees'),
    (55,  'Trees'),
    (56,  'Trees'),
    (57,  'Trees'),
    (58,  'Trees'),
    (59,  'Trees'),
    (60,  'Trees'),
    (61,  'Tries'),
    (62,  'Tries'),
    (63,  'Tries'),
    (64,  'Heap / Priority Queue'),
    (65,  'Heap / Priority Queue'),
    (66,  'Heap / Priority Queue'),
    (67,  'Heap / Priority Queue'),
    (68,  'Heap / Priority Queue'),
    (69,  'Heap / Priority Queue'),
    (70,  'Heap / Priority Queue'),
    (71,  'Backtracking'),
    (72,  'Backtracking'),
    (73,  'Backtracking'),
    (74,  'Backtracking'),
    (75,  'Backtracking'),
    (76,  'Backtracking'),
    (77,  'Backtracking'),
    (78,  'Backtracking'),
    (79,  'Backtracking'),
    (80,  'Graphs'),
    (81,  'Graphs'),
    (82,  'Graphs'),
    (83,  'Graphs'),
    (84,  'Graphs'),
    (85,  'Graphs'),
    (86,  'Graphs'),
    (87,  'Graphs'),
    (88,  'Graphs'),
    (89,  'Graphs'),
    (90,  'Graphs'),
    (91,  'Graphs'),
    (92,  'Graphs'),
    (93,  'Advanced Graphs'),
    (94,  'Advanced Graphs'),
    (95,  'Advanced Graphs'),
    (96,  'Advanced Graphs'),
    (97,  'Advanced Graphs'),
    (98,  'Advanced Graphs'),
    (99,  '1D Dynamic Programming'),
    (100, '1D Dynamic Programming'),
    (101, '1D Dynamic Programming'),
    (102, '1D Dynamic Programming'),
    (103, '1D Dynamic Programming'),
    (104, '1D Dynamic Programming'),
    (105, '1D Dynamic Programming'),
    (106, '1D Dynamic Programming'),
    (107, '1D Dynamic Programming'),
    (108, '1D Dynamic Programming'),
    (109, '1D Dynamic Programming'),
    (110, '1D Dynamic Programming'),
    (111, '2D Dynamic Programming'),
    (112, '2D Dynamic Programming'),
    (113, '2D Dynamic Programming'),
    (114, '2D Dynamic Programming'),
    (115, '2D Dynamic Programming'),
    (116, '2D Dynamic Programming'),
    (117, '2D Dynamic Programming'),
    (118, '2D Dynamic Programming'),
    (119, '2D Dynamic Programming'),
    (120, '2D Dynamic Programming'),
    (121, '2D Dynamic Programming'),
    (122, 'Greedy'),
    (123, 'Greedy'),
    (124, 'Greedy'),
    (125, 'Greedy'),
    (126, 'Greedy'),
    (127, 'Greedy'),
    (128, 'Greedy'),
    (129, 'Greedy'),
    (130, 'Intervals'),
    (131, 'Intervals'),
    (132, 'Intervals'),
    (133, 'Intervals'),
    (134, 'Intervals'),
    (135, 'Intervals'),
    (136, 'Math & Geometry'),
    (137, 'Math & Geometry'),
    (138, 'Math & Geometry'),
    (139, 'Math & Geometry'),
    (140, 'Math & Geometry'),
    (141, 'Math & Geometry'),
    (142, 'Math & Geometry'),
    (143, 'Math & Geometry'),
    (144, 'Bit Manipulation'),
    (145, 'Bit Manipulation'),
    (146, 'Bit Manipulation'),
    (147, 'Bit Manipulation'),
    (148, 'Bit Manipulation'),
    (149, 'Bit Manipulation'),
    (150, 'Bit Manipulation')
) AS upd(pos, section),
problem_lists pl
WHERE pl.slug = 'neetcode-150'
  AND pli.list_id = pl.id
  AND pli.position = upd.pos;

-- ─── New list: Grind 75 ───────────────────────────────────────────────────────
-- Curated by Yang Shun (tech-interview-handbook). Organized by topic, not by week.
-- Missing slugs are silently skipped by the JOIN.
INSERT INTO problem_lists (slug, name, description, source_url, sort_order)
VALUES (
    'grind-75',
    'Grind 75',
    'Yang Shun''s curated 75-problem list for structured interview prep, organized by topic.',
    'https://www.techinterviewhandbook.org/grind75',
    15
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    source_url = EXCLUDED.source_url,
    sort_order = EXCLUDED.sort_order;

WITH items(list_slug, position, section, leetcode_slug) AS (
  VALUES
    -- Array (11)
    ('grind-75',  1, 'Array', 'two-sum'),
    ('grind-75',  2, 'Array', 'best-time-to-buy-and-sell-stock'),
    ('grind-75',  3, 'Array', 'majority-element'),
    ('grind-75',  4, 'Array', 'contains-duplicate'),
    ('grind-75',  5, 'Array', 'maximum-subarray'),
    ('grind-75',  6, 'Array', 'insert-interval'),
    ('grind-75',  7, 'Array', 'merge-intervals'),
    ('grind-75',  8, 'Array', 'product-of-array-except-self'),
    ('grind-75',  9, 'Array', 'combination-sum'),
    ('grind-75', 10, 'Array', 'sort-colors'),
    ('grind-75', 11, 'Array', '3sum'),
    -- String (7)
    ('grind-75', 12, 'String', 'valid-anagram'),
    ('grind-75', 13, 'String', 'valid-palindrome'),
    ('grind-75', 14, 'String', 'longest-substring-without-repeating-characters'),
    ('grind-75', 15, 'String', 'longest-palindromic-substring'),
    ('grind-75', 16, 'String', 'find-all-anagrams-in-a-string'),
    ('grind-75', 17, 'String', 'minimum-window-substring'),
    ('grind-75', 18, 'String', 'roman-to-integer'),
    -- Stack (5)
    ('grind-75', 19, 'Stack', 'valid-parentheses'),
    ('grind-75', 20, 'Stack', 'implement-queue-using-stacks'),
    ('grind-75', 21, 'Stack', 'evaluate-reverse-polish-notation'),
    ('grind-75', 22, 'Stack', 'min-stack'),
    ('grind-75', 23, 'Stack', 'decode-string'),
    -- Linked List (6)
    ('grind-75', 24, 'Linked List', 'merge-two-sorted-lists'),
    ('grind-75', 25, 'Linked List', 'linked-list-cycle'),
    ('grind-75', 26, 'Linked List', 'reverse-linked-list'),
    ('grind-75', 27, 'Linked List', 'middle-of-the-linked-list'),
    ('grind-75', 28, 'Linked List', 'palindrome-linked-list'),
    ('grind-75', 29, 'Linked List', 'lru-cache'),
    -- Binary Tree (12)
    ('grind-75', 30, 'Binary Tree', 'invert-binary-tree'),
    ('grind-75', 31, 'Binary Tree', 'maximum-depth-of-binary-tree'),
    ('grind-75', 32, 'Binary Tree', 'balanced-binary-tree'),
    ('grind-75', 33, 'Binary Tree', 'validate-binary-search-tree'),
    ('grind-75', 34, 'Binary Tree', 'lowest-common-ancestor-of-a-binary-search-tree'),
    ('grind-75', 35, 'Binary Tree', 'lowest-common-ancestor-of-a-binary-tree'),
    ('grind-75', 36, 'Binary Tree', 'binary-tree-level-order-traversal'),
    ('grind-75', 37, 'Binary Tree', 'binary-tree-right-side-view'),
    ('grind-75', 38, 'Binary Tree', 'binary-tree-maximum-path-sum'),
    ('grind-75', 39, 'Binary Tree', 'construct-binary-tree-from-preorder-and-inorder-traversal'),
    ('grind-75', 40, 'Binary Tree', 'kth-smallest-element-in-a-bst'),
    ('grind-75', 41, 'Binary Tree', 'serialize-and-deserialize-binary-tree'),
    -- Graph (9)
    ('grind-75', 42, 'Graph', 'flood-fill'),
    ('grind-75', 43, 'Graph', 'number-of-islands'),
    ('grind-75', 44, 'Graph', 'clone-graph'),
    ('grind-75', 45, 'Graph', 'rotting-oranges'),
    ('grind-75', 46, 'Graph', 'course-schedule'),
    ('grind-75', 47, 'Graph', 'pacific-atlantic-water-flow'),
    ('grind-75', 48, 'Graph', 'number-of-connected-components-in-an-undirected-graph'),
    ('grind-75', 49, 'Graph', 'graph-valid-tree'),
    ('grind-75', 50, 'Graph', 'accounts-merge'),
    -- Heap (5)
    ('grind-75', 51, 'Heap', 'kth-largest-element-in-an-array'),
    ('grind-75', 52, 'Heap', 'task-scheduler'),
    ('grind-75', 53, 'Heap', 'top-k-frequent-elements'),
    ('grind-75', 54, 'Heap', 'find-median-from-data-stream'),
    ('grind-75', 55, 'Heap', 'merge-k-sorted-lists'),
    -- Trie (2)
    ('grind-75', 56, 'Trie', 'implement-trie-prefix-tree'),
    ('grind-75', 57, 'Trie', 'design-add-and-search-words-data-structure'),
    -- Dynamic Programming (10)
    ('grind-75', 58, 'Dynamic Programming', 'climbing-stairs'),
    ('grind-75', 59, 'Dynamic Programming', 'coin-change'),
    ('grind-75', 60, 'Dynamic Programming', 'house-robber'),
    ('grind-75', 61, 'Dynamic Programming', 'decode-ways'),
    ('grind-75', 62, 'Dynamic Programming', 'longest-increasing-subsequence'),
    ('grind-75', 63, 'Dynamic Programming', 'unique-paths'),
    ('grind-75', 64, 'Dynamic Programming', 'partition-equal-subset-sum'),
    ('grind-75', 65, 'Dynamic Programming', 'word-break'),
    ('grind-75', 66, 'Dynamic Programming', 'jump-game'),
    ('grind-75', 67, 'Dynamic Programming', 'jump-game-ii'),
    -- Binary Search (5)
    ('grind-75', 68, 'Binary Search', 'binary-search'),
    ('grind-75', 69, 'Binary Search', 'first-bad-version'),
    ('grind-75', 70, 'Binary Search', 'search-in-rotated-sorted-array'),
    ('grind-75', 71, 'Binary Search', 'time-based-key-value-store'),
    ('grind-75', 72, 'Binary Search', 'find-minimum-in-rotated-sorted-array'),
    -- Recursion (3)
    ('grind-75', 73, 'Recursion', 'generate-parentheses'),
    ('grind-75', 74, 'Recursion', 'permutations'),
    ('grind-75', 75, 'Recursion', 'subsets')
)
INSERT INTO problem_list_items (list_id, position, section, problem_id)
SELECT pl.id, items.position, items.section, p.id
FROM items
JOIN problem_lists pl ON pl.slug = items.list_slug
JOIN problems p ON p.leetcode_slug = items.leetcode_slug
ON CONFLICT (list_id, problem_id) DO NOTHING;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

UPDATE problem_list_items pli
SET section = NULL
FROM problem_lists pl
WHERE pl.slug IN ('blind-75', 'neetcode-150')
  AND pli.list_id = pl.id;

DELETE FROM problem_lists WHERE slug = 'grind-75';

-- +goose StatementEnd
