-- +goose Up
-- +goose StatementBegin

INSERT INTO problem_lists (slug, name, description, source_url, sort_order)
VALUES
  ('leetcode-75',
   'LeetCode 75',
   'Official LeetCode 75 study plan covering core interview patterns.',
   'https://leetcode.com/studyplan/leetcode-75/',
   22),
  ('top-100-liked',
   'Top 100 Liked',
   'Official LeetCode Top 100 Liked study plan grouped by topic.',
   'https://leetcode.com/studyplan/top-100-liked/',
   26),
  ('algomap-100',
   'AlgoMap 100',
   'AlgoMap roadmap: 100 problems across the main data structures and algorithms path.',
   'https://algomap.io/roadmap',
   27),
  ('sean-prashad-patterns',
   'Sean Prashad Patterns',
   'Sean Prashad pattern-based LeetCode list with 178 interview questions.',
   'https://seanprashad.com/leetcode-patterns/',
   28),
  ('meta-top-50',
   'Meta Top 50',
   'Top Meta-tagged problems from Sean Prashad frequency data.',
   'https://seanprashad.com/leetcode-patterns/',
   70),
  ('microsoft-top-50',
   'Microsoft Top 50',
   'Top Microsoft-tagged problems from Sean Prashad frequency data.',
   'https://seanprashad.com/leetcode-patterns/',
   80)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    source_url = EXCLUDED.source_url,
    sort_order = EXCLUDED.sort_order;

-- LeetCode 75
WITH items(list_slug, position, section, leetcode_slug) AS (
  VALUES
    ('leetcode-75',   1, 'Array / String', 'merge-strings-alternately'),
    ('leetcode-75',   2, 'Array / String', 'greatest-common-divisor-of-strings'),
    ('leetcode-75',   3, 'Array / String', 'kids-with-the-greatest-number-of-candies'),
    ('leetcode-75',   4, 'Array / String', 'can-place-flowers'),
    ('leetcode-75',   5, 'Array / String', 'reverse-vowels-of-a-string'),
    ('leetcode-75',   6, 'Array / String', 'reverse-words-in-a-string'),
    ('leetcode-75',   7, 'Array / String', 'product-of-array-except-self'),
    ('leetcode-75',   8, 'Array / String', 'increasing-triplet-subsequence'),
    ('leetcode-75',   9, 'Array / String', 'string-compression'),
    ('leetcode-75',  10, 'Two Pointers', 'move-zeroes'),
    ('leetcode-75',  11, 'Two Pointers', 'is-subsequence'),
    ('leetcode-75',  12, 'Two Pointers', 'container-with-most-water'),
    ('leetcode-75',  13, 'Two Pointers', 'max-number-of-k-sum-pairs'),
    ('leetcode-75',  14, 'Sliding Window', 'maximum-average-subarray-i'),
    ('leetcode-75',  15, 'Sliding Window', 'maximum-number-of-vowels-in-a-substring-of-given-length'),
    ('leetcode-75',  16, 'Sliding Window', 'max-consecutive-ones-iii'),
    ('leetcode-75',  17, 'Sliding Window', 'longest-subarray-of-1s-after-deleting-one-element'),
    ('leetcode-75',  18, 'Prefix Sum', 'find-the-highest-altitude'),
    ('leetcode-75',  19, 'Prefix Sum', 'find-pivot-index'),
    ('leetcode-75',  20, 'Hash Map / Set', 'find-the-difference-of-two-arrays'),
    ('leetcode-75',  21, 'Hash Map / Set', 'unique-number-of-occurrences'),
    ('leetcode-75',  22, 'Hash Map / Set', 'determine-if-two-strings-are-close'),
    ('leetcode-75',  23, 'Hash Map / Set', 'equal-row-and-column-pairs'),
    ('leetcode-75',  24, 'Stack', 'removing-stars-from-a-string'),
    ('leetcode-75',  25, 'Stack', 'asteroid-collision'),
    ('leetcode-75',  26, 'Stack', 'decode-string'),
    ('leetcode-75',  27, 'Queue', 'number-of-recent-calls'),
    ('leetcode-75',  28, 'Queue', 'dota2-senate'),
    ('leetcode-75',  29, 'Linked List', 'delete-the-middle-node-of-a-linked-list'),
    ('leetcode-75',  30, 'Linked List', 'odd-even-linked-list'),
    ('leetcode-75',  31, 'Linked List', 'reverse-linked-list'),
    ('leetcode-75',  32, 'Linked List', 'maximum-twin-sum-of-a-linked-list'),
    ('leetcode-75',  33, 'Binary Tree DFS', 'maximum-depth-of-binary-tree'),
    ('leetcode-75',  34, 'Binary Tree DFS', 'leaf-similar-trees'),
    ('leetcode-75',  35, 'Binary Tree DFS', 'count-good-nodes-in-binary-tree'),
    ('leetcode-75',  36, 'Binary Tree DFS', 'path-sum-iii'),
    ('leetcode-75',  37, 'Binary Tree DFS', 'longest-zigzag-path-in-a-binary-tree'),
    ('leetcode-75',  38, 'Binary Tree DFS', 'lowest-common-ancestor-of-a-binary-tree'),
    ('leetcode-75',  39, 'Binary Tree BFS', 'binary-tree-right-side-view'),
    ('leetcode-75',  40, 'Binary Tree BFS', 'maximum-level-sum-of-a-binary-tree'),
    ('leetcode-75',  41, 'Binary Search Tree', 'search-in-a-binary-search-tree'),
    ('leetcode-75',  42, 'Binary Search Tree', 'delete-node-in-a-bst'),
    ('leetcode-75',  43, 'Graphs DFS', 'keys-and-rooms'),
    ('leetcode-75',  44, 'Graphs DFS', 'number-of-provinces'),
    ('leetcode-75',  45, 'Graphs DFS', 'reorder-routes-to-make-all-paths-lead-to-the-city-zero'),
    ('leetcode-75',  46, 'Graphs DFS', 'evaluate-division'),
    ('leetcode-75',  47, 'Graphs BFS', 'nearest-exit-from-entrance-in-maze'),
    ('leetcode-75',  48, 'Graphs BFS', 'rotting-oranges'),
    ('leetcode-75',  49, 'Heap / Priority Queue', 'kth-largest-element-in-an-array'),
    ('leetcode-75',  50, 'Heap / Priority Queue', 'smallest-number-in-infinite-set'),
    ('leetcode-75',  51, 'Heap / Priority Queue', 'maximum-subsequence-score'),
    ('leetcode-75',  52, 'Heap / Priority Queue', 'total-cost-to-hire-k-workers'),
    ('leetcode-75',  53, 'Binary Search', 'guess-number-higher-or-lower'),
    ('leetcode-75',  54, 'Binary Search', 'successful-pairs-of-spells-and-potions'),
    ('leetcode-75',  55, 'Binary Search', 'find-peak-element'),
    ('leetcode-75',  56, 'Binary Search', 'koko-eating-bananas'),
    ('leetcode-75',  57, 'Backtracking', 'letter-combinations-of-a-phone-number'),
    ('leetcode-75',  58, 'Backtracking', 'combination-sum-iii'),
    ('leetcode-75',  59, 'DP - 1D', 'n-th-tribonacci-number'),
    ('leetcode-75',  60, 'DP - 1D', 'min-cost-climbing-stairs'),
    ('leetcode-75',  61, 'DP - 1D', 'house-robber'),
    ('leetcode-75',  62, 'DP - 1D', 'domino-and-tromino-tiling'),
    ('leetcode-75',  63, 'DP - Multidimensional', 'unique-paths'),
    ('leetcode-75',  64, 'DP - Multidimensional', 'longest-common-subsequence'),
    ('leetcode-75',  65, 'DP - Multidimensional', 'best-time-to-buy-and-sell-stock-with-transaction-fee'),
    ('leetcode-75',  66, 'DP - Multidimensional', 'edit-distance'),
    ('leetcode-75',  67, 'Bit Manipulation', 'counting-bits'),
    ('leetcode-75',  68, 'Bit Manipulation', 'single-number'),
    ('leetcode-75',  69, 'Bit Manipulation', 'minimum-flips-to-make-a-or-b-equal-to-c'),
    ('leetcode-75',  70, 'Trie', 'implement-trie-prefix-tree'),
    ('leetcode-75',  71, 'Trie', 'search-suggestions-system'),
    ('leetcode-75',  72, 'Intervals', 'non-overlapping-intervals'),
    ('leetcode-75',  73, 'Intervals', 'minimum-number-of-arrows-to-burst-balloons'),
    ('leetcode-75',  74, 'Monotonic Stack', 'daily-temperatures'),
    ('leetcode-75',  75, 'Monotonic Stack', 'online-stock-span')
)
INSERT INTO problem_list_items (list_id, position, section, problem_id)
SELECT pl.id, items.position, items.section, p.id
FROM items
JOIN problem_lists pl ON pl.slug = items.list_slug
JOIN problems p ON p.leetcode_slug = items.leetcode_slug
ON CONFLICT (list_id, problem_id) DO NOTHING;

-- Top 100 Liked
WITH items(list_slug, position, section, leetcode_slug) AS (
  VALUES
    ('top-100-liked',   1, 'Backtracking', 'letter-combinations-of-a-phone-number'),
    ('top-100-liked',   2, 'Backtracking', 'generate-parentheses'),
    ('top-100-liked',   3, 'Backtracking', 'combination-sum'),
    ('top-100-liked',   4, 'Backtracking', 'permutations'),
    ('top-100-liked',   5, 'Backtracking', 'n-queens'),
    ('top-100-liked',   6, 'Backtracking', 'subsets'),
    ('top-100-liked',   7, 'Backtracking', 'word-search'),
    ('top-100-liked',   8, 'Backtracking', 'palindrome-partitioning'),
    ('top-100-liked',   9, 'Binary Search', 'median-of-two-sorted-arrays'),
    ('top-100-liked',  10, 'Binary Search', 'search-in-rotated-sorted-array'),
    ('top-100-liked',  11, 'Binary Search', 'find-first-and-last-position-of-element-in-sorted-array'),
    ('top-100-liked',  12, 'Binary Search', 'search-insert-position'),
    ('top-100-liked',  13, 'Binary Search', 'search-a-2d-matrix'),
    ('top-100-liked',  14, 'Binary Search', 'binary-tree-maximum-path-sum'),
    ('top-100-liked',  15, 'Binary Search', 'find-minimum-in-rotated-sorted-array'),
    ('top-100-liked',  16, 'Binary Tree', 'binary-tree-inorder-traversal'),
    ('top-100-liked',  17, 'Binary Tree', 'validate-binary-search-tree'),
    ('top-100-liked',  18, 'Binary Tree', 'symmetric-tree'),
    ('top-100-liked',  19, 'Binary Tree', 'binary-tree-level-order-traversal'),
    ('top-100-liked',  20, 'Binary Tree', 'maximum-depth-of-binary-tree'),
    ('top-100-liked',  21, 'Binary Tree', 'construct-binary-tree-from-preorder-and-inorder-traversal'),
    ('top-100-liked',  22, 'Binary Tree', 'convert-sorted-array-to-binary-search-tree'),
    ('top-100-liked',  23, 'Binary Tree', 'flatten-binary-tree-to-linked-list'),
    ('top-100-liked',  24, 'Binary Tree', 'binary-tree-right-side-view'),
    ('top-100-liked',  25, 'Binary Tree', 'invert-binary-tree'),
    ('top-100-liked',  26, 'Binary Tree', 'kth-smallest-element-in-a-bst'),
    ('top-100-liked',  27, 'Binary Tree', 'lowest-common-ancestor-of-a-binary-tree'),
    ('top-100-liked',  28, 'Binary Tree', 'path-sum-iii'),
    ('top-100-liked',  29, 'Binary Tree', 'diameter-of-binary-tree'),
    ('top-100-liked',  30, 'Dynamic Programming', 'longest-palindromic-substring'),
    ('top-100-liked',  31, 'Dynamic Programming', 'longest-valid-parentheses'),
    ('top-100-liked',  32, 'Dynamic Programming', 'unique-paths'),
    ('top-100-liked',  33, 'Dynamic Programming', 'minimum-path-sum'),
    ('top-100-liked',  34, 'Dynamic Programming', 'climbing-stairs'),
    ('top-100-liked',  35, 'Dynamic Programming', 'edit-distance'),
    ('top-100-liked',  36, 'Dynamic Programming', 'pascals-triangle'),
    ('top-100-liked',  37, 'Dynamic Programming', 'word-break'),
    ('top-100-liked',  38, 'Dynamic Programming', 'maximum-product-subarray'),
    ('top-100-liked',  39, 'Dynamic Programming', 'house-robber'),
    ('top-100-liked',  40, 'Dynamic Programming', 'perfect-squares'),
    ('top-100-liked',  41, 'Dynamic Programming', 'longest-increasing-subsequence'),
    ('top-100-liked',  42, 'Dynamic Programming', 'coin-change'),
    ('top-100-liked',  43, 'Dynamic Programming', 'partition-equal-subset-sum'),
    ('top-100-liked',  44, 'Dynamic Programming', 'longest-common-subsequence'),
    ('top-100-liked',  45, 'Graph', 'number-of-islands'),
    ('top-100-liked',  46, 'Graph', 'course-schedule'),
    ('top-100-liked',  47, 'Graph', 'rotting-oranges'),
    ('top-100-liked',  48, 'Greedy', 'jump-game-ii'),
    ('top-100-liked',  49, 'Greedy', 'jump-game'),
    ('top-100-liked',  50, 'Greedy', 'best-time-to-buy-and-sell-stock'),
    ('top-100-liked',  51, 'Greedy', 'partition-labels'),
    ('top-100-liked',  52, 'Hashing', 'two-sum'),
    ('top-100-liked',  53, 'Hashing', 'group-anagrams'),
    ('top-100-liked',  54, 'Hashing', 'longest-consecutive-sequence'),
    ('top-100-liked',  55, 'Hashing', 'subarray-sum-equals-k'),
    ('top-100-liked',  56, 'Heap', 'kth-largest-element-in-an-array'),
    ('top-100-liked',  57, 'Heap', 'find-median-from-data-stream'),
    ('top-100-liked',  58, 'Heap', 'top-k-frequent-elements'),
    ('top-100-liked',  59, 'Linked Lists', 'add-two-numbers'),
    ('top-100-liked',  60, 'Linked Lists', 'remove-nth-node-from-end-of-list'),
    ('top-100-liked',  61, 'Linked Lists', 'merge-two-sorted-lists'),
    ('top-100-liked',  62, 'Linked Lists', 'merge-k-sorted-lists'),
    ('top-100-liked',  63, 'Linked Lists', 'swap-nodes-in-pairs'),
    ('top-100-liked',  64, 'Linked Lists', 'reverse-nodes-in-k-group'),
    ('top-100-liked',  65, 'Linked Lists', 'copy-list-with-random-pointer'),
    ('top-100-liked',  66, 'Linked Lists', 'linked-list-cycle'),
    ('top-100-liked',  67, 'Linked Lists', 'linked-list-cycle-ii'),
    ('top-100-liked',  68, 'Linked Lists', 'lru-cache'),
    ('top-100-liked',  69, 'Linked Lists', 'sort-list'),
    ('top-100-liked',  70, 'Linked Lists', 'intersection-of-two-linked-lists'),
    ('top-100-liked',  71, 'Linked Lists', 'reverse-linked-list'),
    ('top-100-liked',  72, 'Linked Lists', 'palindrome-linked-list'),
    ('top-100-liked',  73, 'Matrix', 'rotate-image'),
    ('top-100-liked',  74, 'Matrix', 'spiral-matrix'),
    ('top-100-liked',  75, 'Matrix', 'set-matrix-zeroes'),
    ('top-100-liked',  76, 'Matrix', 'search-a-2d-matrix-ii'),
    ('top-100-liked',  77, 'Sliding Window', 'longest-substring-without-repeating-characters'),
    ('top-100-liked',  78, 'Sliding Window', 'minimum-window-substring'),
    ('top-100-liked',  79, 'Sliding Window', 'sliding-window-maximum'),
    ('top-100-liked',  80, 'Sliding Window', 'find-all-anagrams-in-a-string'),
    ('top-100-liked',  81, 'Stack', 'valid-parentheses'),
    ('top-100-liked',  82, 'Stack', 'largest-rectangle-in-histogram'),
    ('top-100-liked',  83, 'Stack', 'min-stack'),
    ('top-100-liked',  84, 'Stack', 'decode-string'),
    ('top-100-liked',  85, 'Stack', 'daily-temperatures'),
    ('top-100-liked',  86, 'Two Pointers', 'container-with-most-water'),
    ('top-100-liked',  87, 'Two Pointers', '3sum'),
    ('top-100-liked',  88, 'Two Pointers', 'trapping-rain-water'),
    ('top-100-liked',  89, 'Two Pointers', 'move-zeroes'),
    ('top-100-liked',  90, 'Trie', 'implement-trie-prefix-tree'),
    ('top-100-liked',  91, 'Miscellaneous', 'next-permutation'),
    ('top-100-liked',  92, 'Miscellaneous', 'first-missing-positive'),
    ('top-100-liked',  93, 'Miscellaneous', 'maximum-subarray'),
    ('top-100-liked',  94, 'Miscellaneous', 'merge-intervals'),
    ('top-100-liked',  95, 'Miscellaneous', 'sort-colors'),
    ('top-100-liked',  96, 'Miscellaneous', 'single-number'),
    ('top-100-liked',  97, 'Miscellaneous', 'majority-element'),
    ('top-100-liked',  98, 'Miscellaneous', 'rotate-array'),
    ('top-100-liked',  99, 'Miscellaneous', 'product-of-array-except-self'),
    ('top-100-liked', 100, 'Miscellaneous', 'find-the-duplicate-number')
)
INSERT INTO problem_list_items (list_id, position, section, problem_id)
SELECT pl.id, items.position, items.section, p.id
FROM items
JOIN problem_lists pl ON pl.slug = items.list_slug
JOIN problems p ON p.leetcode_slug = items.leetcode_slug
ON CONFLICT (list_id, problem_id) DO NOTHING;

-- AlgoMap 100
WITH items(list_slug, position, section, leetcode_slug) AS (
  VALUES
    ('algomap-100',   1, 'Arrays & Strings', 'find-closest-number-to-zero'),
    ('algomap-100',   2, 'Arrays & Strings', 'merge-strings-alternately'),
    ('algomap-100',   3, 'Arrays & Strings', 'roman-to-integer'),
    ('algomap-100',   4, 'Arrays & Strings', 'is-subsequence'),
    ('algomap-100',   5, 'Arrays & Strings', 'best-time-to-buy-and-sell-stock'),
    ('algomap-100',   6, 'Arrays & Strings', 'longest-common-prefix'),
    ('algomap-100',   7, 'Arrays & Strings', 'summary-ranges'),
    ('algomap-100',   8, 'Arrays & Strings', 'product-of-array-except-self'),
    ('algomap-100',   9, 'Arrays & Strings', 'merge-intervals'),
    ('algomap-100',  10, 'Arrays & Strings', 'spiral-matrix'),
    ('algomap-100',  11, 'Arrays & Strings', 'rotate-image'),
    ('algomap-100',  12, 'Hashmaps & Sets', 'jewels-and-stones'),
    ('algomap-100',  13, 'Hashmaps & Sets', 'contains-duplicate'),
    ('algomap-100',  14, 'Hashmaps & Sets', 'ransom-note'),
    ('algomap-100',  15, 'Hashmaps & Sets', 'valid-anagram'),
    ('algomap-100',  16, 'Hashmaps & Sets', 'maximum-number-of-balloons'),
    ('algomap-100',  17, 'Hashmaps & Sets', 'two-sum'),
    ('algomap-100',  18, 'Hashmaps & Sets', 'valid-sudoku'),
    ('algomap-100',  19, 'Hashmaps & Sets', 'group-anagrams'),
    ('algomap-100',  20, 'Hashmaps & Sets', 'majority-element'),
    ('algomap-100',  21, 'Hashmaps & Sets', 'longest-consecutive-sequence'),
    ('algomap-100',  22, '2 Pointers', 'squares-of-a-sorted-array'),
    ('algomap-100',  23, '2 Pointers', 'reverse-string'),
    ('algomap-100',  24, '2 Pointers', 'two-sum-ii-input-array-is-sorted'),
    ('algomap-100',  25, '2 Pointers', 'valid-palindrome'),
    ('algomap-100',  26, '2 Pointers', '3sum'),
    ('algomap-100',  27, '2 Pointers', 'container-with-most-water'),
    ('algomap-100',  28, '2 Pointers', 'trapping-rain-water'),
    ('algomap-100',  29, 'Stacks', 'baseball-game'),
    ('algomap-100',  30, 'Stacks', 'valid-parentheses'),
    ('algomap-100',  31, 'Stacks', 'evaluate-reverse-polish-notation'),
    ('algomap-100',  32, 'Stacks', 'daily-temperatures'),
    ('algomap-100',  33, 'Stacks', 'min-stack'),
    ('algomap-100',  34, 'Linked Lists', 'remove-duplicates-from-sorted-list'),
    ('algomap-100',  35, 'Linked Lists', 'reverse-linked-list'),
    ('algomap-100',  36, 'Linked Lists', 'merge-two-sorted-lists'),
    ('algomap-100',  37, 'Linked Lists', 'linked-list-cycle'),
    ('algomap-100',  38, 'Linked Lists', 'middle-of-the-linked-list'),
    ('algomap-100',  39, 'Linked Lists', 'remove-nth-node-from-end-of-list'),
    ('algomap-100',  40, 'Linked Lists', 'copy-list-with-random-pointer'),
    ('algomap-100',  41, 'Binary Search', 'binary-search'),
    ('algomap-100',  42, 'Binary Search', 'search-insert-position'),
    ('algomap-100',  43, 'Binary Search', 'first-bad-version'),
    ('algomap-100',  44, 'Binary Search', 'valid-perfect-square'),
    ('algomap-100',  45, 'Binary Search', 'search-a-2d-matrix'),
    ('algomap-100',  46, 'Binary Search', 'find-minimum-in-rotated-sorted-array'),
    ('algomap-100',  47, 'Binary Search', 'search-in-rotated-sorted-array'),
    ('algomap-100',  48, 'Binary Search', 'koko-eating-bananas'),
    ('algomap-100',  49, 'Sliding Window', 'maximum-average-subarray-i'),
    ('algomap-100',  50, 'Sliding Window', 'max-consecutive-ones-iii'),
    ('algomap-100',  51, 'Sliding Window', 'longest-substring-without-repeating-characters'),
    ('algomap-100',  52, 'Sliding Window', 'longest-repeating-character-replacement'),
    ('algomap-100',  53, 'Sliding Window', 'minimum-size-subarray-sum'),
    ('algomap-100',  54, 'Sliding Window', 'permutation-in-string'),
    ('algomap-100',  55, 'Trees', 'invert-binary-tree'),
    ('algomap-100',  56, 'Trees', 'maximum-depth-of-binary-tree'),
    ('algomap-100',  57, 'Trees', 'balanced-binary-tree'),
    ('algomap-100',  58, 'Trees', 'diameter-of-binary-tree'),
    ('algomap-100',  59, 'Trees', 'same-tree'),
    ('algomap-100',  60, 'Trees', 'symmetric-tree'),
    ('algomap-100',  61, 'Trees', 'path-sum'),
    ('algomap-100',  62, 'Trees', 'subtree-of-another-tree'),
    ('algomap-100',  63, 'Trees', 'binary-tree-level-order-traversal'),
    ('algomap-100',  64, 'Trees', 'kth-smallest-element-in-a-bst'),
    ('algomap-100',  65, 'Trees', 'minimum-absolute-difference-in-bst'),
    ('algomap-100',  66, 'Trees', 'validate-binary-search-tree'),
    ('algomap-100',  67, 'Trees', 'lowest-common-ancestor-of-a-binary-search-tree'),
    ('algomap-100',  68, 'Trees', 'implement-trie-prefix-tree'),
    ('algomap-100',  69, 'Heaps', 'last-stone-weight'),
    ('algomap-100',  70, 'Heaps', 'kth-largest-element-in-an-array'),
    ('algomap-100',  71, 'Heaps', 'top-k-frequent-elements'),
    ('algomap-100',  72, 'Heaps', 'k-closest-points-to-origin'),
    ('algomap-100',  73, 'Heaps', 'merge-k-sorted-lists'),
    ('algomap-100',  74, 'Recursive Backtracking', 'subsets'),
    ('algomap-100',  75, 'Recursive Backtracking', 'permutations'),
    ('algomap-100',  76, 'Recursive Backtracking', 'combinations'),
    ('algomap-100',  77, 'Recursive Backtracking', 'combination-sum'),
    ('algomap-100',  78, 'Recursive Backtracking', 'letter-combinations-of-a-phone-number'),
    ('algomap-100',  79, 'Recursive Backtracking', 'generate-parentheses'),
    ('algomap-100',  80, 'Recursive Backtracking', 'word-search'),
    ('algomap-100',  81, 'Graphs', 'find-if-path-exists-in-graph'),
    ('algomap-100',  82, 'Graphs', 'number-of-islands'),
    ('algomap-100',  83, 'Graphs', 'max-area-of-island'),
    ('algomap-100',  84, 'Graphs', 'course-schedule'),
    ('algomap-100',  85, 'Graphs', 'course-schedule-ii'),
    ('algomap-100',  86, 'Graphs', 'pacific-atlantic-water-flow'),
    ('algomap-100',  87, 'Graphs', 'clone-graph'),
    ('algomap-100',  88, 'Graphs', 'rotting-oranges'),
    ('algomap-100',  89, 'Graphs', 'min-cost-to-connect-all-points'),
    ('algomap-100',  90, 'Graphs', 'network-delay-time'),
    ('algomap-100',  91, 'Dynamic Programming', 'fibonacci-number'),
    ('algomap-100',  92, 'Dynamic Programming', 'climbing-stairs'),
    ('algomap-100',  93, 'Dynamic Programming', 'min-cost-climbing-stairs'),
    ('algomap-100',  94, 'Dynamic Programming', 'house-robber'),
    ('algomap-100',  95, 'Dynamic Programming', 'unique-paths'),
    ('algomap-100',  96, 'Dynamic Programming', 'maximum-subarray'),
    ('algomap-100',  97, 'Dynamic Programming', 'jump-game'),
    ('algomap-100',  98, 'Dynamic Programming', 'coin-change'),
    ('algomap-100',  99, 'Dynamic Programming', 'longest-increasing-subsequence'),
    ('algomap-100', 100, 'Dynamic Programming', 'longest-common-subsequence')
)
INSERT INTO problem_list_items (list_id, position, section, problem_id)
SELECT pl.id, items.position, items.section, p.id
FROM items
JOIN problem_lists pl ON pl.slug = items.list_slug
JOIN problems p ON p.leetcode_slug = items.leetcode_slug
ON CONFLICT (list_id, problem_id) DO NOTHING;

-- Sean Prashad Patterns
WITH items(list_slug, position, section, leetcode_slug) AS (
  VALUES
    ('sean-prashad-patterns',   1, 'Array', 'two-sum'),
    ('sean-prashad-patterns',   2, 'Linked List', 'add-two-numbers'),
    ('sean-prashad-patterns',   3, 'Hash Table', 'longest-substring-without-repeating-characters'),
    ('sean-prashad-patterns',   4, 'Array', 'median-of-two-sorted-arrays'),
    ('sean-prashad-patterns',   5, 'Two Pointers', 'longest-palindromic-substring'),
    ('sean-prashad-patterns',   6, 'Array', 'container-with-most-water'),
    ('sean-prashad-patterns',   7, 'Array', '3sum'),
    ('sean-prashad-patterns',   8, 'Array', '3sum-closest'),
    ('sean-prashad-patterns',   9, 'Hash Table', 'letter-combinations-of-a-phone-number'),
    ('sean-prashad-patterns',  10, 'Linked List', 'remove-nth-node-from-end-of-list'),
    ('sean-prashad-patterns',  11, 'Linked List', 'merge-two-sorted-lists'),
    ('sean-prashad-patterns',  12, 'String', 'generate-parentheses'),
    ('sean-prashad-patterns',  13, 'Linked List', 'merge-k-sorted-lists'),
    ('sean-prashad-patterns',  14, 'Linked List', 'swap-nodes-in-pairs'),
    ('sean-prashad-patterns',  15, 'Linked List', 'reverse-nodes-in-k-group'),
    ('sean-prashad-patterns',  16, 'Hash Table', 'substring-with-concatenation-of-all-words'),
    ('sean-prashad-patterns',  17, 'Array', 'search-in-rotated-sorted-array'),
    ('sean-prashad-patterns',  18, 'Array', 'sudoku-solver'),
    ('sean-prashad-patterns',  19, 'Array', 'combination-sum'),
    ('sean-prashad-patterns',  20, 'Array', 'combination-sum-ii'),
    ('sean-prashad-patterns',  21, 'Array', 'first-missing-positive'),
    ('sean-prashad-patterns',  22, 'Array', 'trapping-rain-water'),
    ('sean-prashad-patterns',  23, 'Array', 'permutations'),
    ('sean-prashad-patterns',  24, 'Array', 'permutations-ii'),
    ('sean-prashad-patterns',  25, 'Array', 'rotate-image'),
    ('sean-prashad-patterns',  26, 'Array', 'n-queens'),
    ('sean-prashad-patterns',  27, 'Array', 'maximum-subarray'),
    ('sean-prashad-patterns',  28, 'Array', 'spiral-matrix'),
    ('sean-prashad-patterns',  29, 'Array', 'jump-game'),
    ('sean-prashad-patterns',  30, 'Array', 'merge-intervals'),
    ('sean-prashad-patterns',  31, 'Array', 'insert-interval'),
    ('sean-prashad-patterns',  32, 'Linked List', 'rotate-list'),
    ('sean-prashad-patterns',  33, 'Math', 'unique-paths'),
    ('sean-prashad-patterns',  34, 'Math', 'climbing-stairs'),
    ('sean-prashad-patterns',  35, 'Array', 'set-matrix-zeroes'),
    ('sean-prashad-patterns',  36, 'Array', 'search-a-2d-matrix'),
    ('sean-prashad-patterns',  37, 'Array', 'sort-colors'),
    ('sean-prashad-patterns',  38, 'Hash Table', 'minimum-window-substring'),
    ('sean-prashad-patterns',  39, 'Backtracking', 'combinations'),
    ('sean-prashad-patterns',  40, 'Array', 'subsets'),
    ('sean-prashad-patterns',  41, 'Array', 'word-search'),
    ('sean-prashad-patterns',  42, 'Array', 'search-in-rotated-sorted-array-ii'),
    ('sean-prashad-patterns',  43, 'Linked List', 'remove-duplicates-from-sorted-list'),
    ('sean-prashad-patterns',  44, 'Array', 'subsets-ii'),
    ('sean-prashad-patterns',  45, 'String', 'decode-ways'),
    ('sean-prashad-patterns',  46, 'Linked List', 'reverse-linked-list-ii'),
    ('sean-prashad-patterns',  47, 'Tree', 'validate-binary-search-tree'),
    ('sean-prashad-patterns',  48, 'Tree', 'same-tree'),
    ('sean-prashad-patterns',  49, 'Tree', 'binary-tree-level-order-traversal'),
    ('sean-prashad-patterns',  50, 'Tree', 'binary-tree-zigzag-level-order-traversal'),
    ('sean-prashad-patterns',  51, 'Tree', 'maximum-depth-of-binary-tree'),
    ('sean-prashad-patterns',  52, 'Array', 'construct-binary-tree-from-preorder-and-inorder-traversal'),
    ('sean-prashad-patterns',  53, 'Tree', 'binary-tree-level-order-traversal-ii'),
    ('sean-prashad-patterns',  54, 'Tree', 'minimum-depth-of-binary-tree'),
    ('sean-prashad-patterns',  55, 'Tree', 'path-sum'),
    ('sean-prashad-patterns',  56, 'Backtracking', 'path-sum-ii'),
    ('sean-prashad-patterns',  57, 'Array', 'best-time-to-buy-and-sell-stock'),
    ('sean-prashad-patterns',  58, 'Dynamic Programming', 'binary-tree-maximum-path-sum'),
    ('sean-prashad-patterns',  59, 'Array', 'longest-consecutive-sequence'),
    ('sean-prashad-patterns',  60, 'String', 'palindrome-partitioning'),
    ('sean-prashad-patterns',  61, 'Array', 'gas-station'),
    ('sean-prashad-patterns',  62, 'Array', 'single-number'),
    ('sean-prashad-patterns',  63, 'Array', 'word-break'),
    ('sean-prashad-patterns',  64, 'Hash Table', 'linked-list-cycle'),
    ('sean-prashad-patterns',  65, 'Hash Table', 'linked-list-cycle-ii'),
    ('sean-prashad-patterns',  66, 'Linked List', 'reorder-list'),
    ('sean-prashad-patterns',  67, 'Linked List', 'sort-list'),
    ('sean-prashad-patterns',  68, 'Array', 'maximum-product-subarray'),
    ('sean-prashad-patterns',  69, 'Array', 'find-minimum-in-rotated-sorted-array'),
    ('sean-prashad-patterns',  70, 'Array', 'find-peak-element'),
    ('sean-prashad-patterns',  71, 'Array', 'majority-element'),
    ('sean-prashad-patterns',  72, 'Array', 'house-robber'),
    ('sean-prashad-patterns',  73, 'Tree', 'binary-tree-right-side-view'),
    ('sean-prashad-patterns',  74, 'Array', 'number-of-islands'),
    ('sean-prashad-patterns',  75, 'Linked List', 'remove-linked-list-elements'),
    ('sean-prashad-patterns',  76, 'Linked List', 'reverse-linked-list'),
    ('sean-prashad-patterns',  77, 'Depth-First Search', 'course-schedule'),
    ('sean-prashad-patterns',  78, 'Hash Table', 'implement-trie-prefix-tree'),
    ('sean-prashad-patterns',  79, 'Array', 'minimum-size-subarray-sum'),
    ('sean-prashad-patterns',  80, 'Depth-First Search', 'course-schedule-ii'),
    ('sean-prashad-patterns',  81, 'Array', 'word-search-ii'),
    ('sean-prashad-patterns',  82, 'Array', 'house-robber-ii'),
    ('sean-prashad-patterns',  83, 'Array', 'kth-largest-element-in-an-array'),
    ('sean-prashad-patterns',  84, 'Array', 'combination-sum-iii'),
    ('sean-prashad-patterns',  85, 'Array', 'contains-duplicate'),
    ('sean-prashad-patterns',  86, 'Tree', 'invert-binary-tree'),
    ('sean-prashad-patterns',  87, 'Tree', 'kth-smallest-element-in-a-bst'),
    ('sean-prashad-patterns',  88, 'Linked List', 'palindrome-linked-list'),
    ('sean-prashad-patterns',  89, 'Tree', 'lowest-common-ancestor-of-a-binary-search-tree'),
    ('sean-prashad-patterns',  90, 'Tree', 'lowest-common-ancestor-of-a-binary-tree'),
    ('sean-prashad-patterns',  91, 'Array', 'product-of-array-except-self'),
    ('sean-prashad-patterns',  92, 'Array', 'sliding-window-maximum'),
    ('sean-prashad-patterns',  93, 'Array', 'search-a-2d-matrix-ii'),
    ('sean-prashad-patterns',  94, 'Array', 'meeting-rooms'),
    ('sean-prashad-patterns',  95, 'Array', 'meeting-rooms-ii'),
    ('sean-prashad-patterns',  96, 'Backtracking', 'factor-combinations'),
    ('sean-prashad-patterns',  97, 'String', 'binary-tree-paths'),
    ('sean-prashad-patterns',  98, 'Depth-First Search', 'graph-valid-tree'),
    ('sean-prashad-patterns',  99, 'Array', 'missing-number'),
    ('sean-prashad-patterns', 100, 'Array', 'alien-dictionary'),
    ('sean-prashad-patterns', 101, 'Array', 'move-zeroes'),
    ('sean-prashad-patterns', 102, 'Array', 'find-the-duplicate-number'),
    ('sean-prashad-patterns', 103, 'Two Pointers', 'find-median-from-data-stream'),
    ('sean-prashad-patterns', 104, 'String', 'serialize-and-deserialize-binary-tree'),
    ('sean-prashad-patterns', 105, 'Array', 'longest-increasing-subsequence'),
    ('sean-prashad-patterns', 106, 'Array', 'range-sum-query-immutable'),
    ('sean-prashad-patterns', 107, 'Array', 'best-time-to-buy-and-sell-stock-with-cooldown'),
    ('sean-prashad-patterns', 108, 'Depth-First Search', 'minimum-height-trees'),
    ('sean-prashad-patterns', 109, 'String', 'generalized-abbreviation'),
    ('sean-prashad-patterns', 110, 'Array', 'coin-change'),
    ('sean-prashad-patterns', 111, 'Depth-First Search', 'number-of-connected-components-in-an-undirected-graph'),
    ('sean-prashad-patterns', 112, 'Array', 'count-of-range-sum'),
    ('sean-prashad-patterns', 113, 'Linked List', 'odd-even-linked-list'),
    ('sean-prashad-patterns', 114, 'Dynamic Programming', 'counting-bits'),
    ('sean-prashad-patterns', 115, 'Array', 'top-k-frequent-elements'),
    ('sean-prashad-patterns', 116, 'Hash Table', 'rearrange-string-k-distance-apart'),
    ('sean-prashad-patterns', 117, 'Array', 'find-k-pairs-with-smallest-sums'),
    ('sean-prashad-patterns', 118, 'Array', 'combination-sum-iv'),
    ('sean-prashad-patterns', 119, 'Array', 'kth-smallest-element-in-a-sorted-matrix'),
    ('sean-prashad-patterns', 120, 'Two Pointers', 'is-subsequence'),
    ('sean-prashad-patterns', 121, 'Array', 'partition-equal-subset-sum'),
    ('sean-prashad-patterns', 122, 'Array', 'pacific-atlantic-water-flow'),
    ('sean-prashad-patterns', 123, 'Hash Table', 'longest-repeating-character-replacement'),
    ('sean-prashad-patterns', 124, 'Array', 'word-squares'),
    ('sean-prashad-patterns', 125, 'Array', 'non-overlapping-intervals'),
    ('sean-prashad-patterns', 126, 'Tree', 'path-sum-iii'),
    ('sean-prashad-patterns', 127, 'Array', 'find-all-duplicates-in-an-array'),
    ('sean-prashad-patterns', 128, 'Array', 'find-all-numbers-disappeared-in-an-array'),
    ('sean-prashad-patterns', 129, 'Hash Table', 'sort-characters-by-frequency'),
    ('sean-prashad-patterns', 130, 'Array', 'minimum-number-of-arrows-to-burst-balloons'),
    ('sean-prashad-patterns', 131, 'Array', 'concatenated-words'),
    ('sean-prashad-patterns', 132, 'Array', 'sliding-window-median'),
    ('sean-prashad-patterns', 133, 'Array', 'target-sum'),
    ('sean-prashad-patterns', 134, 'Hash Table', 'permutation-in-string'),
    ('sean-prashad-patterns', 135, 'Tree', 'subtree-of-another-tree'),
    ('sean-prashad-patterns', 136, 'Tree', 'merge-two-binary-trees'),
    ('sean-prashad-patterns', 137, 'Array', 'task-scheduler'),
    ('sean-prashad-patterns', 138, 'Array', 'smallest-range-covering-elements-from-k-lists'),
    ('sean-prashad-patterns', 139, 'Tree', 'average-of-levels-in-binary-tree'),
    ('sean-prashad-patterns', 140, 'String', 'design-search-autocomplete-system'),
    ('sean-prashad-patterns', 141, 'Array', 'maximum-average-subarray-i'),
    ('sean-prashad-patterns', 142, 'Two Pointers', 'palindromic-substrings'),
    ('sean-prashad-patterns', 143, 'Array', 'maximum-binary-tree'),
    ('sean-prashad-patterns', 144, 'Array', 'find-k-closest-elements'),
    ('sean-prashad-patterns', 145, 'Tree', 'maximum-width-of-binary-tree'),
    ('sean-prashad-patterns', 146, 'Array', 'number-of-longest-increasing-subsequence'),
    ('sean-prashad-patterns', 147, 'Array', 'partition-to-k-equal-sum-subsets'),
    ('sean-prashad-patterns', 148, 'Array', 'subarray-product-less-than-k'),
    ('sean-prashad-patterns', 149, 'Array', 'longest-word-in-dictionary'),
    ('sean-prashad-patterns', 150, 'Array', 'find-smallest-letter-greater-than-target'),
    ('sean-prashad-patterns', 151, 'Array', 'prefix-and-suffix-search'),
    ('sean-prashad-patterns', 152, 'Array', 'employee-free-time'),
    ('sean-prashad-patterns', 153, 'Hash Table', 'reorganize-string'),
    ('sean-prashad-patterns', 154, 'Array', 'binary-search'),
    ('sean-prashad-patterns', 155, 'String', 'letter-case-permutation'),
    ('sean-prashad-patterns', 156, 'Hash Table', 'count-unique-characters-of-all-substrings-of-a-given-string'),
    ('sean-prashad-patterns', 157, 'Two Pointers', 'backspace-string-compare'),
    ('sean-prashad-patterns', 158, 'Array', 'peak-index-in-a-mountain-array'),
    ('sean-prashad-patterns', 159, 'Hash Table', 'all-nodes-distance-k-in-binary-tree'),
    ('sean-prashad-patterns', 160, 'Linked List', 'middle-of-the-linked-list'),
    ('sean-prashad-patterns', 161, 'Hash Table', 'maximum-frequency-stack'),
    ('sean-prashad-patterns', 162, 'Array', 'fruit-into-baskets'),
    ('sean-prashad-patterns', 163, 'Array', 'k-closest-points-to-origin'),
    ('sean-prashad-patterns', 164, 'Array', 'squares-of-a-sorted-array'),
    ('sean-prashad-patterns', 165, 'Array', 'interval-list-intersections'),
    ('sean-prashad-patterns', 166, 'Array', 'index-pairs-of-a-string'),
    ('sean-prashad-patterns', 167, 'Array', 'convert-1d-array-into-2d-array'),
    ('sean-prashad-patterns', 168, 'Hash Table', 'valid-anagram'),
    ('sean-prashad-patterns', 169, 'Array', 'group-anagrams'),
    ('sean-prashad-patterns', 170, 'Array', 'encode-and-decode-strings'),
    ('sean-prashad-patterns', 171, 'Two Pointers', 'valid-palindrome'),
    ('sean-prashad-patterns', 172, 'String', 'valid-parentheses'),
    ('sean-prashad-patterns', 173, 'String', 'design-add-and-search-words-data-structure'),
    ('sean-prashad-patterns', 174, 'Hash Table', 'clone-graph'),
    ('sean-prashad-patterns', 175, 'Divide and Conquer', 'number-of-1-bits'),
    ('sean-prashad-patterns', 176, 'Divide and Conquer', 'reverse-bits'),
    ('sean-prashad-patterns', 177, 'Math', 'sum-of-two-integers'),
    ('sean-prashad-patterns', 178, 'String', 'longest-common-subsequence')
)
INSERT INTO problem_list_items (list_id, position, section, problem_id)
SELECT pl.id, items.position, items.section, p.id
FROM items
JOIN problem_lists pl ON pl.slug = items.list_slug
JOIN problems p ON p.leetcode_slug = items.leetcode_slug
ON CONFLICT (list_id, problem_id) DO NOTHING;

-- Meta Top 50
WITH items(list_slug, position, section, leetcode_slug) AS (
  VALUES
    ('meta-top-50',   1, 'Array', 'two-sum'),
    ('meta-top-50',   2, 'Array', 'best-time-to-buy-and-sell-stock'),
    ('meta-top-50',   3, 'Two Pointers', 'valid-palindrome'),
    ('meta-top-50',   4, 'String', 'valid-parentheses'),
    ('meta-top-50',   5, 'Math', 'climbing-stairs'),
    ('meta-top-50',   6, 'Tree', 'binary-tree-right-side-view'),
    ('meta-top-50',   7, 'Array', 'median-of-two-sorted-arrays'),
    ('meta-top-50',   8, 'Tree', 'lowest-common-ancestor-of-a-binary-tree'),
    ('meta-top-50',   9, 'Array', 'group-anagrams'),
    ('meta-top-50',  10, 'Array', 'find-peak-element'),
    ('meta-top-50',  11, 'Array', 'majority-element'),
    ('meta-top-50',  12, 'Array', 'number-of-islands'),
    ('meta-top-50',  13, 'Linked List', 'palindrome-linked-list'),
    ('meta-top-50',  14, 'Two Pointers', 'palindromic-substrings'),
    ('meta-top-50',  15, 'Array', '3sum'),
    ('meta-top-50',  16, 'Linked List', 'merge-two-sorted-lists'),
    ('meta-top-50',  17, 'Array', 'merge-intervals'),
    ('meta-top-50',  18, 'Linked List', 'add-two-numbers'),
    ('meta-top-50',  19, 'String', 'generate-parentheses'),
    ('meta-top-50',  20, 'Array', 'maximum-subarray'),
    ('meta-top-50',  21, 'Array', 'kth-largest-element-in-an-array'),
    ('meta-top-50',  22, 'Array', 'contains-duplicate'),
    ('meta-top-50',  23, 'Array', 'top-k-frequent-elements'),
    ('meta-top-50',  24, 'Array', 'k-closest-points-to-origin'),
    ('meta-top-50',  25, 'Hash Table', 'longest-substring-without-repeating-characters'),
    ('meta-top-50',  26, 'Array', 'container-with-most-water'),
    ('meta-top-50',  27, 'Array', '3sum-closest'),
    ('meta-top-50',  28, 'Array', 'search-in-rotated-sorted-array'),
    ('meta-top-50',  29, 'Array', 'first-missing-positive'),
    ('meta-top-50',  30, 'Array', 'set-matrix-zeroes'),
    ('meta-top-50',  31, 'Backtracking', 'combinations'),
    ('meta-top-50',  32, 'Depth-First Search', 'course-schedule'),
    ('meta-top-50',  33, 'Array', 'minimum-size-subarray-sum'),
    ('meta-top-50',  34, 'Hash Table', 'valid-anagram'),
    ('meta-top-50',  35, 'Array', 'alien-dictionary'),
    ('meta-top-50',  36, 'Array', 'kth-smallest-element-in-a-sorted-matrix'),
    ('meta-top-50',  37, 'Array', 'maximum-average-subarray-i'),
    ('meta-top-50',  38, 'Hash Table', 'all-nodes-distance-k-in-binary-tree'),
    ('meta-top-50',  39, 'Two Pointers', 'longest-palindromic-substring'),
    ('meta-top-50',  40, 'Linked List', 'remove-nth-node-from-end-of-list'),
    ('meta-top-50',  41, 'Linked List', 'merge-k-sorted-lists'),
    ('meta-top-50',  42, 'Array', 'combination-sum'),
    ('meta-top-50',  43, 'Array', 'trapping-rain-water'),
    ('meta-top-50',  44, 'Array', 'permutations'),
    ('meta-top-50',  45, 'Array', 'rotate-image'),
    ('meta-top-50',  46, 'Array', 'search-a-2d-matrix'),
    ('meta-top-50',  47, 'Array', 'sort-colors'),
    ('meta-top-50',  48, 'Array', 'subsets'),
    ('meta-top-50',  49, 'Tree', 'validate-binary-search-tree'),
    ('meta-top-50',  50, 'Array', 'construct-binary-tree-from-preorder-and-inorder-traversal')
)
INSERT INTO problem_list_items (list_id, position, section, problem_id)
SELECT pl.id, items.position, items.section, p.id
FROM items
JOIN problem_lists pl ON pl.slug = items.list_slug
JOIN problems p ON p.leetcode_slug = items.leetcode_slug
ON CONFLICT (list_id, problem_id) DO NOTHING;

-- Microsoft Top 50
WITH items(list_slug, position, section, leetcode_slug) AS (
  VALUES
    ('microsoft-top-50',   1, 'Array', 'two-sum'),
    ('microsoft-top-50',   2, 'Hash Table', 'longest-substring-without-repeating-characters'),
    ('microsoft-top-50',   3, 'Array', 'trapping-rain-water'),
    ('microsoft-top-50',   4, 'Linked List', 'add-two-numbers'),
    ('microsoft-top-50',   5, 'Array', 'number-of-islands'),
    ('microsoft-top-50',   6, 'String', 'generate-parentheses'),
    ('microsoft-top-50',   7, 'Array', 'maximum-subarray'),
    ('microsoft-top-50',   8, 'Array', 'merge-intervals'),
    ('microsoft-top-50',   9, 'Array', 'find-peak-element'),
    ('microsoft-top-50',  10, 'Two Pointers', 'longest-palindromic-substring'),
    ('microsoft-top-50',  11, 'Linked List', 'remove-nth-node-from-end-of-list'),
    ('microsoft-top-50',  12, 'Hash Table', 'minimum-window-substring'),
    ('microsoft-top-50',  13, 'Array', 'spiral-matrix'),
    ('microsoft-top-50',  14, 'Array', 'meeting-rooms-ii'),
    ('microsoft-top-50',  15, 'Two Pointers', 'find-median-from-data-stream'),
    ('microsoft-top-50',  16, 'Array', '3sum'),
    ('microsoft-top-50',  17, 'Array', 'search-in-rotated-sorted-array'),
    ('microsoft-top-50',  18, 'Array', 'insert-interval'),
    ('microsoft-top-50',  19, 'Array', 'search-a-2d-matrix'),
    ('microsoft-top-50',  20, 'Hash Table', 'all-nodes-distance-k-in-binary-tree'),
    ('microsoft-top-50',  21, 'Array', 'container-with-most-water'),
    ('microsoft-top-50',  22, 'Linked List', 'merge-k-sorted-lists'),
    ('microsoft-top-50',  23, 'Array', 'construct-binary-tree-from-preorder-and-inorder-traversal'),
    ('microsoft-top-50',  24, 'Array', 'best-time-to-buy-and-sell-stock'),
    ('microsoft-top-50',  25, 'Two Pointers', 'valid-palindrome'),
    ('microsoft-top-50',  26, 'Array', 'find-minimum-in-rotated-sorted-array'),
    ('microsoft-top-50',  27, 'Array', 'longest-increasing-subsequence'),
    ('microsoft-top-50',  28, 'Array', 'target-sum'),
    ('microsoft-top-50',  29, 'Array', 'median-of-two-sorted-arrays'),
    ('microsoft-top-50',  30, 'Hash Table', 'letter-combinations-of-a-phone-number'),
    ('microsoft-top-50',  31, 'Array', 'n-queens'),
    ('microsoft-top-50',  32, 'Math', 'climbing-stairs'),
    ('microsoft-top-50',  33, 'Array', 'subsets'),
    ('microsoft-top-50',  34, 'Tree', 'binary-tree-zigzag-level-order-traversal'),
    ('microsoft-top-50',  35, 'Tree', 'minimum-depth-of-binary-tree'),
    ('microsoft-top-50',  36, 'String', 'palindrome-partitioning'),
    ('microsoft-top-50',  37, 'Hash Table', 'linked-list-cycle'),
    ('microsoft-top-50',  38, 'Hash Table', 'linked-list-cycle-ii'),
    ('microsoft-top-50',  39, 'Array', 'house-robber'),
    ('microsoft-top-50',  40, 'Depth-First Search', 'course-schedule'),
    ('microsoft-top-50',  41, 'Array', 'sliding-window-maximum'),
    ('microsoft-top-50',  42, 'Hash Table', 'valid-anagram'),
    ('microsoft-top-50',  43, 'String', 'serialize-and-deserialize-binary-tree'),
    ('microsoft-top-50',  44, 'Array', 'coin-change'),
    ('microsoft-top-50',  45, 'Linked List', 'odd-even-linked-list'),
    ('microsoft-top-50',  46, 'String', 'valid-parentheses'),
    ('microsoft-top-50',  47, 'Linked List', 'reverse-nodes-in-k-group'),
    ('microsoft-top-50',  48, 'Array', 'permutations'),
    ('microsoft-top-50',  49, 'Array', 'rotate-image'),
    ('microsoft-top-50',  50, 'Array', 'group-anagrams')
)
INSERT INTO problem_list_items (list_id, position, section, problem_id)
SELECT pl.id, items.position, items.section, p.id
FROM items
JOIN problem_lists pl ON pl.slug = items.list_slug
JOIN problems p ON p.leetcode_slug = items.leetcode_slug
ON CONFLICT (list_id, problem_id) DO NOTHING;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DELETE FROM problem_lists
WHERE slug IN (
  'leetcode-75',
  'top-100-liked',
  'algomap-100',
  'sean-prashad-patterns',
  'meta-top-50',
  'microsoft-top-50'
);
-- +goose StatementEnd
